trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  MINCONDA_VERSION: "latest"
  MINCONDA_LINUX: "Linux-x86_64"

steps:


- script: |
    MINCONDA_OS=$MINCONDA_LINUX
    wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    hash -r
    conda install -y -c conda-forge mamba
    mamba install -y nb_conda nbconvert jupyter_client imageio matplotlib scipy scikit-learn scikit-image ipywidgets astropy
    mamba update -y nb_conda nb_conda_kernels 
    mamba install -y -c conda-forge opencv igl meshplot
    pip install higra trimesh[easy]
  displayName: 'Install miniconda and python packages'
  
 
- script: |
    pwd
    whoami
    ls -l data
    $HOME/miniconda/bin/python test_notebooks.py
  displayName: 'Execute notebooks'
 